cloud:
  aws:
    credentials:
      access-key: AKIARVOIOJEMLKPYGHGY
      secret-key: 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 
      bucket-url: http://revtech2-frontend-beta.s3-website-us-east-1.amazonaws.com/

    region:
      static: us-east-2
    stack: 
      auto: false

application:
  bucket:
    name: revtechphotobucket

spring:
  servlet:
    multipart:
     enabled: true
     file-size-threshold: 2MB
     max-file-size: 5MB
     max-request-size: 10MB

server:
  port: 7777